camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
camera_preprocessing:
  image_width: 512
  image_height: 512
stop_line_positions:
    - [8.0, 16.2]
use_tensorflow_detection: True
use_tensorflow_nth_frame: 2
tensorflow_graph_path: 'light_classification/fcn_graph/checkpoint'
tensorflow_confidence_thesh_green: 0.85
tensorflow_confidence_thesh_yellow: 0.85
tensorflow_confidence_thesh_red: 0.85
detections_filter_size: 6
no_detections_filter_size: 10
no_detections_threshold: 0.6
state_count_threshold: 12
